more updates
Signed-off-by: Maxwell Elliott <maxwell@elliott.now>

more updates

Signed-off-by: Maxwell Elliott <maxwell@elliott.now>

Add proxy build mode

Lay the groundwork for build with proxy integration

Signed-off-by: Maxwell Elliott <maxwell@elliott.now>

more updates

Signed-off-by: Maxwell Elliott <maxwell@elliott.now>

more updates

Signed-off-by: Maxwell Elliott <maxwell@elliott.now>

more updates

Signed-off-by: Maxwell Elliott <maxwell@elliott.now>

Adds SwiftBuild rspm dep

Getting started adding SwiftBuild rspm dep

Seeing the following error when running this `bazelisk build @swiftpkg_swift_build//:SwiftBuild.rspm`:

```terminal
error: ambiguous implicit access level for import of 'TSCBasic'; it is imported as 'private' elsewhere
    |        `- note: silence these warnings by adopting the upcoming feature 'InternalImportsByDefault'
```

Signed-off-by: Maxwell Elliott <maxwell@elliott.now>

swiftbuild is building

updates

cont

Signed-off-by: Maxwell Elliott <maxwell@elliott.now>

need to debug swift build in rules xcodeproj

Signed-off-by: Maxwell Elliott <maxwell@elliott.now>

cont

Signed-off-by: Maxwell Elliott <maxwell@elliott.now>

rollback bazel build swift-build for now

Signed-off-by: Maxwell Elliott <maxwell@elliott.now>